/**
 * Hello World App
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * The \"OPTIONS\" HTTP method is used for the CORS preflight request. Basically, the client browser is asking the server for permission to send the real HTTP request. 
 */
export interface DefaultCORSResponse { 
}
